# Generated by Django 5.2.5 on 2025-08-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_navbar', models.FileField(blank=True, null=True, upload_to='core/site_settings')),
                ('logo_navbar_alt_data', models.CharField(blank=True, help_text='Add data for increasing SEO performance', max_length=255, null=True)),
                ('logo_footer', models.FileField(blank=True, null=True, upload_to='core/site_settings')),
                ('logo_footer_alt_data', models.CharField(blank=True, help_text='Add data for increasing SEO performance', max_length=255, null=True)),
                ('favicon', models.FileField(blank=True, null=True, upload_to='core/site_settings')),
                ('favicon_alt_data', models.CharField(blank=True, help_text='Add data for increasing SEO performance', max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=15, max_digits=17, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=15, max_digits=17, null=True)),
                ('iframe', models.TextField(blank=True, help_text='Just paste iframe src data from googlemap', null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, help_text='Enter phone number starting with the code', max_length=255, null=True)),
                ('fax', models.CharField(blank=True, help_text='Enter fax number starting with the code', max_length=255, null=True)),
                ('facebook', models.URLField(blank=True, help_text='Enter your facebook url', max_length=255, null=True)),
                ('instagram', models.URLField(blank=True, help_text='Enter your instagram url', max_length=255, null=True)),
                ('twitter', models.URLField(blank=True, help_text='Enter your twitter url', max_length=255, null=True)),
                ('linkedin', models.URLField(blank=True, help_text='Enter your linkedin url', max_length=255, null=True)),
                ('youtube', models.URLField(blank=True, help_text='Enter your youtube url', max_length=255, null=True)),
                ('website', models.URLField(blank=True, help_text='Enter your website url', max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
