# Generated by Django 5.2.5 on 2025-08-20 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='ContactUs',
        ),
    ]
