# Generated by Django 5.2.5 on 2025-08-20 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_contact_contactus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
